export const ROUTES = {
  HOME: "/",
  INSTRUCTORS: "/instructors",
  FEATURES: "/features",
  FEATURE_AI_LEARNING: "/features/ai-learning",
  FEATURE_LEARNING_EXPERIENCE: "/features/learning-experience",
  FEATURE_TEACHING_TOOLS: "/features/teaching-tools",
  FEATURE_ORGANIZATION: "/features/organization",
  FEATURE_COMMUNITY: "/features/community",
  PRICING: "/pricing",
  RESOURCES: "/resources",
  RESOURCE_BLOG: "/resources/blog",
  RESOURCE_DOCUMENTATION: "/resources/documentation",
  RESOURCE_HELP_CENTER: "/resources/help-center",
  RESOURCE_COMMUNITY: "/resources/community",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  VERIFY_EMAIL: "/verify-email",
  RESET_PASSWORD: "/reset-password",
  PORTAL: "/portal",
  STUDIO: "/studio",
  ADMIN: "/admin",
  COURSE_DETAILS: "/courses/:slug",
  ABOUT: "/about",
  CAREERS: "/careers",
  CONTACT: "/contact",
  FAQ: "/faq",
  PRIVACY: "/legal/privacy",
  TERMS: "/legal/terms",
  COOKIE: "/legal/cookie",
  CHANGELOG: "/changelog",
  STATUS: "/status",
} as const;

export type RoutePath = (typeof ROUTES)[keyof typeof ROUTES];
